version: "3"
services:
  postgres:
    image: "postgres:latest"
  redis:
    image: "redis:latest"
  server:
    build:
      dockerfile: Dockerfile.dev
      # specific where to get the dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules # ignore this folder
      - ./server:/app # copy another folder
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
